[Xfdashboard Theme]
Name=xfdashboard-moranga
Name[es]=Tablero Xf moranga
Name[sr]=Полетник Моранга
Comment=Moranga theme for xfdashboard
Comment[es]=Tema Moranga para el Tablero Xf
Comment[sr]=Тема полетника моранга
Style=xfdashboard-moranga.css
Layout=xfdashboard.xml;xfdashboard-secondary.xml
Effects=effects.xml
Author=lacios
Version=0.3.10git.154feca
Screenshot=screenshot-xfdashboard-moranga.png
