[Xfdashboard Theme]
Name=xfdashboard
Name[fr]=xfdashboard
Name[sr]=полетник иксфцеа
Comment=Default theme for xfdashboard
Comment[es]=Tema predeterminado para el Tablero Xf
Comment[fr]=Thème par défaut pour xfdashboard
Comment[he]=ערכת נושא ברירת מחדל עבור xfdashboard
Comment[sr]=Подразумевана тема полетника
Style=xfdashboard.css
Layout=xfdashboard.xml;xfdashboard-secondary.xml
Effects=effects.xml
Author=Stephan Haller
Version=0.4.2git.cafce64
Screenshot=screenshot-xfdashboard.png
