[Xfdashboard Theme]
Name=xfdashboard-mint
Name[fr]=xfdashboard-menthe
Name[sr]=полетник-мента
Comment=Fresh-green flavored theme for xfdashboard
Comment[es]=Tema color verde para el Tablero Xf
Comment[fr]=Thème aromatisées vert-frais pour xfdashboard
Comment[sr]=Свежа зелена тема полетника
Style=xfdashboard-mint.css
Layout=xfdashboard.xml;xfdashboard-secondary.xml
Effects=effects.xml
Author=lacios
Version=0.4.2git.cafce64
Screenshot=screenshot-xfdashboard-mint.png
