[Xfdashboard Theme]
Name=xfdashboard-wine
Name[es]=Tablero Xf vino
Name[fr]=xfdashboard-vin
Name[sr]=Полетник у вину
Comment=Red wine theme for xfdashboard
Comment[es]=Tema de color rojo vino para el Tablero Xf
Comment[fr]=Thème vin rouge pour xfdashboard
Comment[sr]=Тема полетника у боји црвеног вина
Style=xfdashboard-wine.css
Layout=xfdashboard.xml;xfdashboard-secondary.xml
Effects=effects.xml
Author=lacios
Version=0.4.2git.cafce64
Screenshot=screenshot-xfdashboard-wine.png
