[Xfdashboard Theme]
Name=xfdashboard-dark
Name[es]=Tablero Xf oscuro
Name[fr]=sombre xfdashboard
Name[sr]=Полетник тамни
Comment=Dark theme for xfdashboard
Comment[es]=Tema oscuro para el Tablero Xf
Comment[fr]=Thème sombre pour xfdashboard
Comment[sr]=Тамна тема полетника
Style=xfdashboard-dark.css
Layout=xfdashboard.xml;xfdashboard-secondary.xml
Effects=effects.xml
Author=lacios
Version=0.4.2git.cafce64
Screenshot=screenshot-xfdashboard-dark.png
